<ns0:test-suite xmlns:ns0="urn:model.allure.qatools.yandex.ru" start="1595774472847" stop="1595774473027">
  <name>scripts</name>
  <labels/>
  <test-cases>
    <test-case start="1595774472847" status="passed" stop="1595774472868">
      <name>test_login.TestLogin.test_login1</name>
      <attachments/>
      <labels>
        <label name="severity" value="normal"/>
        <label name="thread" value="16364-MainThread"/>
        <label name="host" value="DESKTOP-JVGKKG8"/>
        <label name="framework" value="pytest"/>
        <label name="language" value="cpython3"/>
      </labels>
      <steps/>
    </test-case>
    <test-case start="1595774472928" status="passed" stop="1595774472953">
      <name>test_login.TestLogin.test_login2</name>
      <attachments/>
      <labels>
        <label name="severity" value="normal"/>
        <label name="thread" value="16364-MainThread"/>
        <label name="host" value="DESKTOP-JVGKKG8"/>
        <label name="framework" value="pytest"/>
        <label name="language" value="cpython3"/>
      </labels>
      <steps/>
    </test-case>
    <test-case start="1595774473002" status="failed" stop="1595774473027">
      <name>test_login.TestLogin.test_login3</name>
      <failure>
        <message>AssertionError: assert 0</message>
        <stack-trace>self = &lt;scripts.test_login.TestLogin object at 0x08187CB8&gt;

    def test_login3(self):
&gt;       assert 0
E       assert 0

scripts\test_login.py:9: AssertionError</stack-trace>
      </failure>
      <attachments/>
      <labels>
        <label name="severity" value="normal"/>
        <label name="thread" value="16364-MainThread"/>
        <label name="host" value="DESKTOP-JVGKKG8"/>
        <label name="framework" value="pytest"/>
        <label name="language" value="cpython3"/>
      </labels>
      <steps/>
    </test-case>
  </test-cases>
</ns0:test-suite>
